export enum DocTypes {
    Audio = "audio",
    Image = 'image',
    Video = 'video',
}
export enum DocExtention {
    PDF = ".PDF",
    TXT = ".TXT",
    CSS = ".CSS",
    HTML = "HTML",
    PHP = ".PHP",
    C = ".C",
    CPP = ".CPP",
    H = ".H",
    HPP = ".HPP",
    JS = ".JS",
    DOC = ".DOC",
    DOCX = ".DOCX",
    XLS = ".XLS",
    XLSX = ".XLSX",
    PPT = ".PPT",
    PPTX = ".PPTX",
    PAGES = ".PAGES",
    AI = ".AI",
    PSD = ".PSD",
    TIFF = ".TIFF",
    DXF = ".DXF",
    /*SVG = ".SVG",*/
    EPS = ".EPS",
    PS = ".PS",
    TTF = ".TTF",
    XPS = ".XPS",
    ZIP = ".ZIP",
    RAR = ".RAR",
    JSON = ".JSON"
}