export const captureEditForm = [
  {
    type: 'tabs',
    key: 'tabs',
    components: [
      // ── Display Tab ────────────────────────────────────────────────────────
      {
        key: 'display',
        label: 'Display',
        weight: 0,
        components: [
          {
            weight: 0,
            type: 'textfield',
            input: true,
            key: 'label',
            label: 'Label',
            placeholder: 'Field Label',
            tooltip: 'The label for this field that will appear next to it.',
            validate: { required: true },
          },
          {
            weight: 100,
            type: 'textarea',
            input: true,
            key: 'description',
            label: 'Description',
            placeholder: 'Description for this field.',
            tooltip: 'The description is text that will appear below the input field.',
            editor: 'ace',
            as: 'html',
            wysiwyg: { minLines: 3, isUseWorkerDisabled: true },
          },
          {
            weight: 200,
            type: 'textarea',
            input: true,
            key: 'tooltip',
            label: 'Tooltip',
            placeholder: 'To add a tooltip to this field, enter text here.',
            tooltip: 'Adds a tooltip to the side of this field.',
            editor: 'ace',
            as: 'html',
            wysiwyg: { minLines: 3, isUseWorkerDisabled: true },
          },
          {
            weight: 1100,
            type: 'checkbox',
            label: 'Hidden',
            tooltip: 'A hidden field is still a part of the form, but is hidden from view.',
            key: 'hidden',
            input: true,
          },
          {
            weight: 1200,
            type: 'checkbox',
            label: 'Hide Label',
            tooltip: 'Hide the label of this component.',
            key: 'hideLabel',
            input: true,
          },
          {
            weight: 1400,
            type: 'checkbox',
            label: 'Disabled',
            tooltip: 'Disable the form input.',
            key: 'disabled',
            input: true,
          },
          {
            weight: 1500,
            type: 'checkbox',
            label: 'Table View',
            tooltip: 'Shows this value within the table view of the submissions.',
            key: 'tableView',
            input: true,
          },
        ],
      },

      // ── File (Camera) Tab ──────────────────────────────────────────────────
      {
        key: 'file',
        label: 'File',
        weight: 5,
        components: [
          {
            type: 'select',
            input: true,
            key: 'storage',
            label: 'Storage',
            weight: 0,
            placeholder: 'Select your file storage provider',
            tooltip: 'Which storage to use when saving the captured image.',
            defaultValue: 'base64',
            data: {
              values: [
                { label: 'Base64 (inline)', value: 'base64' },
                { label: 'URL', value: 'url' },
                { label: 'S3', value: 's3' },
                { label: 'Azure', value: 'azure' },
              ],
            },
          },
          {
            type: 'textfield',
            input: true,
            key: 'url',
            label: 'Upload URL',
            weight: 10,
            placeholder: 'Enter the URL to upload files to.',
            tooltip: 'The URL to upload images to when using URL storage.',
            conditional: {
              json: { '!==': [{ var: 'data.storage' }, 'base64'] },
            },
          },
          {
            type: 'textfield',
            input: true,
            key: 'dir',
            label: 'Directory',
            weight: 20,
            placeholder: 'Optional path to upload the file to.',
            tooltip: 'The directory to upload files to. Will be created if it does not exist.',
            conditional: {
              json: { '!==': [{ var: 'data.storage' }, 'base64'] },
            },
          },
          {
            type: 'textfield',
            input: true,
            key: 'fileNameTemplate',
            label: 'File Name Template',
            weight: 30,
            placeholder: 'E.g. {{timestamp}}.{{format}}',
            tooltip: 'Naming template for captured files. Supports {{timestamp}} and {{format}}.',
          },
          {
            type: 'checkbox',
            input: true,
            key: 'multiple',
            label: 'Allow Multiple',
            weight: 40,
            tooltip: 'Allow multiple photos to be captured.',
          },
          {
            type: 'textfield',
            input: true,
            key: 'fileMaxSize',
            label: 'Maximum File Size (MB)',
            weight: 50,
            placeholder: 'e.g. 5',
            tooltip: 'Maximum size of a captured image in megabytes.',
          },
          {
            type: 'checkbox',
            input: true,
            key: 'image',
            label: 'Display as Image',
            weight: 60,
            defaultValue: true,
            tooltip: 'Show captured image thumbnails inline.',
          },
          {
            type: 'textfield',
            input: true,
            key: 'imageSize',
            label: 'Image Size',
            weight: 70,
            placeholder: 'e.g. 200',
            tooltip: 'Display width of the thumbnail (in pixels). Leave blank for auto.',
            conditional: {
              show: true,
              when: 'image',
              eq: true,
            },
          },
          {
            type: 'checkbox',
            input: true,
            key: 'showWatermark',
            label: 'Show Watermark',
            weight: 80,
            defaultValue: false,
            tooltip: 'Stamp the capture date and time onto the image after taking the photo.',
          },
          {
            type: 'select',
            input: true,
            key: 'watermarkPosition',
            label: 'Watermark Position',
            weight: 81,
            defaultValue: 'bottom-right',
            tooltip: 'Corner of the image where the date/time watermark will be placed.',
            data: {
              values: [
                { label: 'Top Left',      value: 'top-left'      },
                { label: 'Top Center',    value: 'top-center'    },
                { label: 'Top Right',     value: 'top-right'     },
                { label: 'Bottom Left',   value: 'bottom-left'   },
                { label: 'Bottom Center', value: 'bottom-center' },
                { label: 'Bottom Right',  value: 'bottom-right'  },
              ],
            },
            conditional: {
              show: true,
              when: 'showWatermark',
              eq: true,
            },
          },
          {
            type: 'checkbox',
            input: true,
            key: 'showLocationWatermark',
            label: 'Add Watermark Location',
            weight: 82,
            defaultValue: false,
            tooltip: 'Stamp the GPS coordinates (latitude & longitude) onto the image after taking the photo.',
          },
          {
            type: 'select',
            input: true,
            key: 'locationWatermarkPosition',
            label: 'Location Watermark Position',
            weight: 83,
            defaultValue: 'bottom-right',
            tooltip: 'Corner of the image where the GPS coordinates watermark will be placed.',
            data: {
              values: [
                { label: 'Top Left',      value: 'top-left'      },
                { label: 'Top Center',    value: 'top-center'    },
                { label: 'Top Right',     value: 'top-right'     },
                { label: 'Bottom Left',   value: 'bottom-left'   },
                { label: 'Bottom Center', value: 'bottom-center' },
                { label: 'Bottom Right',  value: 'bottom-right'  },
              ],
            },
            conditional: {
              show: true,
              when: 'showLocationWatermark',
              eq: true,
            },
          },
        ],
      },

      // ── Validation Tab ─────────────────────────────────────────────────────
      {
        key: 'validation',
        label: 'Validation',
        weight: 20,
        components: [
          {
            weight: 10,
            type: 'checkbox',
            label: 'Required',
            tooltip: 'A required field must be filled in before the form can be submitted.',
            key: 'validate.required',
            input: true,
          },
          {
            weight: 200,
            key: 'validate.customMessage',
            label: 'Custom Error Message',
            placeholder: 'Custom Error Message',
            type: 'textfield',
            tooltip: 'Error message displayed if any error occurred.',
            input: true,
          },
          {
            type: 'panel',
            title: 'Custom Validation',
            collapsible: true,
            collapsed: true,
            style: { 'margin-bottom': '10px' },
            key: 'custom-validation-js',
            weight: 300,
            components: [
              {
                type: 'textarea',
                key: 'validate.custom',
                rows: 5,
                editor: 'ace',
                hideLabel: true,
                as: 'javascript',
                input: true,
              },
              {
                type: 'htmlelement',
                tag: 'div',
                content:
                  '<p>Enter custom validation code.</p><p>Assign the <strong>valid</strong> variable as either <strong>true</strong> or an error message if validation fails.</p>',
              },
            ],
          },
        ],
      },

      // ── API Tab ───────────────────────────────────────────────────────────
      {
        label: 'API',
        key: 'api',
        weight: 30,
        components: [
          {
            weight: 0,
            type: 'textfield',
            input: true,
            key: 'key',
            label: 'Property Name',
            tooltip: 'The name of this field in the API endpoint.',
            validate: {
              pattern: '(\\w|\\w[\\w-.]*\\w)',
              patternMessage:
                'The property name must only contain alphanumeric characters, underscores, dots and dashes.',
              required: true,
            },
          },
          {
            weight: 100,
            type: 'tags',
            input: true,
            label: 'Field Tags',
            storeas: 'array',
            tooltip: 'Tag the field for use in custom logic.',
            key: 'tags',
          },
        ],
      },

      // ── Conditional Tab ───────────────────────────────────────────────────
      {
        label: 'Conditional',
        key: 'conditional',
        weight: 40,
        components: [
          {
            type: 'panel',
            title: 'Simple',
            key: 'simple-conditional',
            theme: 'default',
            components: [
              {
                type: 'select',
                input: true,
                label: 'This component should Display:',
                key: 'conditional.show',
                dataSrc: 'values',
                data: {
                  values: [
                    { label: 'True', value: 'true' },
                    { label: 'False', value: 'false' },
                  ],
                },
              },
              {
                type: 'select',
                input: true,
                label: 'When the form component:',
                key: 'conditional.when',
                dataSrc: 'custom',
                valueProperty: 'value',
                data: {},
              },
              {
                type: 'textfield',
                input: true,
                label: 'Has the value:',
                key: 'conditional.eq',
              },
            ],
          },
          {
            type: 'panel',
            title: 'Advanced Conditions',
            theme: 'default',
            collapsible: true,
            collapsed: true,
            key: 'customConditionalPanel',
            weight: 110,
            components: [
              {
                type: 'textarea',
                key: 'customConditional',
                rows: 5,
                editor: 'ace',
                hideLabel: true,
                as: 'javascript',
                input: true,
              },
              {
                type: 'htmlelement',
                tag: 'div',
                content:
                  '<p>Enter custom conditional logic. Assign the <strong>show</strong> variable to a boolean result.</p>' +
                  '<h5>Example:</h5><pre>show = data.companyName !== "";</pre>',
              },
            ],
          },
        ],
      },

      // ── Logic Tab ────────────────────────────────────────────────────────
      {
        label: 'Logic',
        key: 'logic',
        weight: 50,
        components: [
          {
            type: 'datagrid',
            input: true,
            label: 'Logic',
            key: 'logic',
            tooltip: 'Add logic to this component.',
            weight: 0,
            components: [
              {
                label: 'Name',
                key: 'name',
                input: true,
                type: 'textfield',
              },
            ],
          },
        ],
      },
    ],
  },
];
